apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-owner
  namespace: app-tenant-team-c
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-owner
  namespace: app-tenant-team-c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-owner
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: app-tenant-team-c-admin@example.com
